name       : libbonobo
version    : 2.32.1
release    : 5
source     :
    - https://download.gnome.org/sources/libbonobo/2.32/libbonobo-2.32.1.tar.bz2 : 9160d4f277646400d3bb6b4fa73636cc6d1a865a32b9d0760e1e9e6ee624976b
license    :
    - GPL-2.0
    - LGPL-2.1
summary    : libbonobo is the non-GUI part of the bonobo component infrastructure
component  : programming
description: |
    libbonobo is the non-GUI part of the bonobo component infrastructure, it is most useful for creating aggregate interfaces & doing IPC easily.
builddeps  :
    - pkgconfig(ORBit-2.0)
    - pkgconfig(popt)
    - intltool
rundeps    :
    - pyorbit
setup      : |
    sed -i "s#-DG_DISABLE_DEPRECATED##" activation-server/Makefile.in
    %configure --disable-static
build      : |
    %make -j1
install    : |
    %make_install
